### ISSUE TITLE
Tags for each version change

### ISSUE THREAD

**Issue by cst152** [Unleash/unleash-docker#10]
Hi,

I have integrated this repository into an automated deployment process and I think it would be really helpful if there were a tag on this repository for each Unleash version bump in the package.json.

Thanks a bunch!

**Comment by ivarconr** [comment]
I agree! 

Would it also make sense to publish the image to docker-hub?

**Comment by cst152** [comment]
If you want to invest the time to maintain a page on Docker Hub, it surely can't hurt :)

**Comment by ivarconr** [comment]
Added a tag for latest version at-least. 
https://github.com/Unleash/unleash-docker/tree/v3.1.1/

Currently I have a lot on my plate, so could take some time before I can invest the required time. This repo was primarily created to provide an example on how you typically would run unleash on docker, but I haven't devoted much love in to the setup :/

Would you be interested in setting up a docker hub page and establish a pipeline/process to push updates?

**Comment by ivarconr** [comment]
More work done in #11
