### ISSUE TITLE
Automated Docker Hub image

### ISSUE THREAD

**Issue by mikesir87** [Unleash/unleash-docker#11]
Since this project doesn't need to build the actual project and is simply used to create the Docker image, you can easily take advantage of Docker Hub's automated build processes. I use this for several projects and it's super easy (and nice). Any push to the repo would automatically trigger a build and automatic push to Docker Hub. Tags in the repo end up being tags on the final image too.

Info: https://docs.docker.com/docker-hub/builds/

**Comment by ivarconr** [comment]
wow nice. I will look in to this!

**Comment by ivarconr** [comment]
I have set this up now, with automated builds for master and tags: 
https://hub.docker.com/r/unleashorg/unleash-server/

Does the setup look ok? Would you @mikesir87 like to be added to the team and help set this up in a sane way? 

E.g. Not tags are named as `release-3.1.1`. But would it make sense to allow people to use `unleashorg/unleash-server:3.1` and get always get the latest patch version?

**Comment by mikesir87** [comment]
Fantastic! It's always nice to have an "official" image from the source owners, rather than rely on an image someone else created. You just never know if it'll be maintained in the long run. So, thanks for setting it all up!

If you want me to help do a sanity check, sure! But, I don't have a ton of extra time to be considered a long-term member. Totally your call! Always happy to help out where I can!

If you want to do the patched version updates, the way I've seen it done most of the time is maintain a branch named `3.1`. When updates occur on that, simply update that branch. Git-wise, it probably makes since to update those branches and merge/fast-forward the changes (at least for the newest release branch) back onto master so they don't diverge too much. Then, use tags for the individual releases as you already are doing. 👍

**Comment by ivarconr** [comment]
Great, I have added you as a collaborator to both this github repo and the unleashorg on Docker Hub. 

It seems like the automatic build process on docker hub is unable to automatically pick up numbered tags (3.1, 3.1.1) and build those. Would you mind have quick look and see if you see something stupid with the current configuration?

**Comment by mikesir87** [comment]
Ok. I'll take a look sometime within the next few hours. 👍

**Comment by ivarconr** [comment]
I finally sorted it out. So it seems like the documentation to trigger on tags is just wrong and this seems to have solved it: https://github.com/docker/hub-feedback/issues/384#issuecomment-197457820
