### ISSUE TITLE
Credentials, API or otherwise in docker image

### ISSUE THREAD

**Issue by mhussain** [Unleash/unleash-docker#14]
Hello 

Whats the best way to enable authentication for unleash server if one uses simply the docker image?

Thanks

**Comment by ivarconr** [comment]
Currently the hosted image does not support this, so the best way would be to create your own docker-project and provide the authentication hooks you need. 

But it would be nice if this docker image could support that, i.e. that one could copy the pre-hook as a plain js-file or similar. 
PR welcomed :+1:

**Comment by evanstucker-hates-2fa** [comment]
I created a PR to fix this: https://github.com/Unleash/unleash-docker/pull/25
