### ISSUE TITLE
DATABASE_URL_FILE can be removed once latest Unleash is depended upon

### ISSUE THREAD

**Issue by Enrico2** [Unleash/unleash-docker#19]
When a release that includes https://github.com/Unleash/unleash/commit/b2ce6f7a48a72cd542489b99a5f6389f249ff2e1 is used as a dependency in this package, the explicit use of `DATABASE_URL_FILE` can be removed.

https://github.com/Unleash/unleash-docker/blob/1af27964d3b0a4e761203ec5fac9b93ff954ebae/index.js#L8-L10

**Comment by ivarconr** [comment]
thanks for reminding me! :fire:
