### ISSUE TITLE
Startup import

### ISSUE THREAD

**Issue by blacroix** [Unleash/unleash-docker#21]
Hi,

Is it possible to use [startup import](https://unleash.github.io/docs/import_export#startup-import) with Docker image? 

Tried to define `IMPORT_FILE` environment variable with path to `export.yml` but variable doesn't seem to be used.

Thanks

**Comment by ivarconr** [comment]
jeah, this is not supported as an environment variable. Options could be extended to accept this i guess. 

adding this to https://github.com/Unleash/unleash-docker/blob/master/index.js#L6 would probably do the trick:
```
let options = {
  importFile: process.env.IMPORT_FILE
}

```
