### ISSUE TITLE
Docker images falling behind Unleash releases

### ISSUE THREAD

**Issue by lagren** [Unleash/unleash-docker#22]
Current Docker release of `unleashorg/unleash-server` is `3.2.14`
Current release of unleash is `3.2.18`

Is it possible to get an official docker image of the latest release?

**Comment by ivarconr** [comment]
It's actually 3.2.20 that's the latest. Will look in to it soon

**Comment by timpeeters** [comment]
Pull request to update to the latest unleash-server version 3.2.22 if it helps:

https://github.com/Unleash/unleash-docker/pull/23

**Comment by ivarconr** [comment]
Must find a way to automate this.
