### ISSUE TITLE
Upgrade unleash to version 3.7.0

### ISSUE THREAD

**Issue by SanderSmee** [Unleash/unleash-docker#32]
Since a new version of unleash is released; can a new docker image be created?

**Comment by ivarconr** [comment]
solved in 22a9f58. Will take a few minutes for docker hub to build them all. 

![image](https://user-images.githubusercontent.com/158948/100245240-1d3ad100-2f38-11eb-9ea3-64d552603e09.png)

**Comment by SanderSmee** [comment]
That was lightning fast. Thank you.
