### ISSUE TITLE
Run on other port than 4242

### ISSUE THREAD

**Issue by henrik242** [Unleash/unleash-docker#38]
An option to pass environment variable (e.g. `SERVER_PORT`) to run unleash on a different port than `4242` (e.g. `80`) would be awesome.

**Comment by henrik242** [comment]
Specifying `HTTP_PORT: 80` in docker-compose.yml works, all is good 👍

Maybe document this?

**Comment by ivarconr** [comment]
It is already in the user documentation. 

https://docs.getunleash.ai/docs/configuring_unleash

**Comment by henrik242** [comment]
Yup, that's where I found it.  But it would be helpful having it here as well.  Thanks anyway :)
