### ISSUE TITLE
Create user accounts using docker-compose

### ISSUE THREAD

**Issue by arlyon** [Unleash/unleash-docker#45]
Hello, I'd like to evaluate unleashed and have spun up a local instance but it is not clear how to create user accounts. Do you have any guidance here? I am happy to submit a PR to the readme with the solution (even if that is just 'look at the docs here').

thanks!

**Comment by ivarconr** [comment]
Yeah, this is not super clear in the README. We just released V4 and have not got around to update all the docs yet. 

You automatically get a user:
username: admin
password: unleash4all

**Comment by ivarconr** [comment]
https://docs.getunleash.io/docs/deploy/getting_started
