### ISSUE TITLE
Push arm64 arch Docker container

### ISSUE THREAD

**Issue by william00179** [Unleash/unleash-docker#52]
Hi,

I have the need to run this service on the arm64 platform. 

I have built unleash-server and unleash-proxy as multi-arch images and published them to unblock my team, but it would be great if the official images supported arm64 along with amd64.

I noted your unleash-proxy repo was already using buildx to build your images so my PR there was simple, https://github.com/Unleash/unleash-proxy/pull/30.

As you are dynamically generating your Dockerfile in this repo, it may be slightly more involved to create a PR for this change.

There is as a small change needed to the Dockerfile in order to build on arm64 due to https://github.com/kelektiv/node.bcrypt.js/ not having pre-built binaries for the architecture. These are only added to the build stage.

```
FROM node:14-alpine as builder
 
RUN apk add --no-cache python3 py3-pip make g++

WORKDIR /unleash
...
```
If there is interest in this, I'm happy to contribute a PR to update the script that builds the PR, however, I will need some help with the GitHub actions as I'm not familiar with this tool.

**Comment by ivarconr** [comment]
@william00179 we switched to bcrypt-js in the latest Unleash release. Feel free to add arm images.

**Comment by chriswk** [comment]
So, we've updated the build to use buildx and qemu, so henceforth when we tag images we'll push arm64 as well as amd64.

Closing this one.
