### ISSUE TITLE
Failed to migrate db OperationalError: connect ECONNREFUSED 192.168.32.2:5432

### ISSUE THREAD

**Issue by danieleliyahu** [Unleash/unleash-docker#53]
I do clone to the docker compose and run it and that the error I get :
Failed to migrate db OperationalError: connect ECONNREFUSED 192.168.32.2:5432

**Comment by bjartwolf** [comment]
It could be https://github.com/Unleash/unleash-docker/issues/54
I saw the same error.... Maybe slightly more motivated now to replicate it too that I see a similar issue.

**Comment by ivarconr** [comment]
should be solved via #53
