### ISSUE TITLE
Errors with starting postgres-alpine

### ISSUE THREAD

**Issue by bjartwolf** [Unleash/unleash-docker#54]
I had issues with starting the docker images with postgres-alpine. 
I think the issue was https://github.com/docker-library/postgres/issues/501

I just removed -alpine and use the standard image... That fixed it for me.

Have not submitted a PR, since I did not dig into it, but it is worth looking into if one wants to keep the alpine image.

**Comment by ivarconr** [comment]
alpine works on my computer though. 

```
➜  ~ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

```
