### ISSUE TITLE
One of the modules is being flagged as malware

### ISSUE THREAD

**Issue by dvdgitman** [Unleash/unleash-docker#74]
### Describe the feature request

I suggest you remove the following module:

node_modules/es5-5ext/_postinstall.js

![Our security team has found the following:](https://i.ibb.co/vBTtgN2/Screenshot-2022-07-14-143917.png)

### Background

After our company decided to switch over to unleash and deploy it on EC2, our security team scanned the container with unleash installed on it and found that `node_modules/es5-5ext/_postinstall.js` is being flagged as a malware.

**Comment by Tymek** [comment]
Thank you for pointing it out. It doesn't look high severity. We will address it soon.

**Comment by Tymek** [comment]
> Really nice catch here!
> - https://github.com/Unleash/unleash/pull/1853#pullrequestreview-1050696659

Fix will be out in next release.

**Comment by dvdgitman** [comment]
Cool! Thank you!
