### ISSUE TITLE
Docker Hub 2 digit version

### ISSUE THREAD

**Issue by luizcarlosfaria** [Unleash/unleash-docker#76]
### Describe the feature request

Looking on docker hub i've found these 3 tags pointing to same version [3489cd0bc7fb](https://hub.docker.com/layers/unleashorg/unleash-server/latest/images/sha256-3489cd0bc7fb04fbefefae3bee8a1cf8fa7a458929ae96334deee3bec54f3cef?context=explore).

- `unleashorg/unleash-server:latest`
- `unleashorg/unleash-server:4`
- `unleashorg/unleash-server:4.14.5`

but the version `unleashorg/unleash-server:4.14` does not exists.

cc @chriswk

### Background

Is usual when build docker images, produces 4 tags per build

- `latest`
- `1` major 
- `1.1` major and minor
-  `1.1.1` major, minor and patch

Looking for the history of tags on docker hub, my judgment that it can was forgot in last release.

**Comment by gastonfournier** [comment]
Hi @luizcarlosfaria thanks for the report! I believe our publish script is missing that version: https://github.com/Unleash/unleash-docker/runs/7126462514?check_suite_focus=true

```
Docker tags
  unleashorg/unleash-server:4.13.0
  unleashorg/unleash-server:4
  unleashorg/unleash-server:latest
```

I'll talk about it with @chriswk
