### ISSUE TITLE
Startup sequence of docker-compose services are wrong

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-docker#78]
### Describe the bug

When starting from a fresh machine with docker/docker-compose installed, the unleash container starts up before postgres is ready, this causes the unleash container to not successfully start and http://localhost:4242 to not respond 

### Steps to reproduce the bug

Without a postgres container or an unleash container already started.
1. Clone the repo
2. cd into the repo folder
3. docker-compose up

### Expected behavior

Postgres, Unleash and Unleash-proxy all to start successfully

### Logs, error output, etc.

```bash
unleash-docker-web-1    | [2022-09-08T06:37:27.113] [ERROR] server-impl.js - Failed to migrate db OperationalError: connect ECONNREFUSED 172.18.0.2:5432
unleash-docker-web-1    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
unleash-docker-web-1    |   cause: Error: connect ECONNREFUSED 172.18.0.2:5432
unleash-docker-web-1    |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
unleash-docker-web-1    |     errno: -111,
unleash-docker-web-1    |     code: 'ECONNREFUSED',
unleash-docker-web-1    |     syscall: 'connect',
unleash-docker-web-1    |     address: '172.18.0.2',
unleash-docker-web-1    |     port: 5432
unleash-docker-web-1    |   },
unleash-docker-web-1    |   isOperational: true,
unleash-docker-web-1    |   errno: -111,
unleash-docker-web-1    |   code: 'ECONNREFUSED',
unleash-docker-web-1    |   syscall: 'connect',
unleash-docker-web-1    |   address: '172.18.0.2',
unleash-docker-web-1    |   port: 5432
unleash-docker-web-1    | }
unleash-docker-web-1    | [ERROR] Error: connect ECONNREFUSED 172.18.0.2:5432
unleash-docker-web-1    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
```
```


### Screenshots

_No response_

### Additional context

Currently, the workaround is to simply stop the compose services and then start them again. But it gives our users a poor first-time experience

### Unleash version

4.14

### Subscription type

_No response_

### Hosting type

_No response_

### SDK information (language and version)

_No response_

**Comment by sighphyre** [comment]
Closed by #80

**Comment by Andrija-Markovic** [comment]
I am using `Docker Compose version v2.10.2` and `Docker version 20.10.17, build 100c701` on Windows OS. This is my first time cloning this repo. I followed the [instructions for working locally with the repo](https://github.com/Unleash/unleash-docker#work-locally-with-this-repo) and I keep getting this error inside the `web` container:
`/usr/local/bin/docker-entrypoint.sh: exec: line 11: ./wait-for: not found`

I tried also running `docker-compose restart web`, but that just results in the same error getting printed inside the container.

Can you help me get unleashed up and running locally?

**Comment by sighphyre** [comment]
Hi @Andrija-Markovic, please can I ask you to open new issues if you're having trouble, we don't keep a close eye on closed issues and we noticed this completely by chance, 6 days after you posted it.

This seems to be an issue related to Windows, we can confirm this does work with WSL though, would you mind giving that a spin and seeing if that helps you out? If you don't come right with that, would you mind opening a new issue or reaching out to us on Slack?

**Comment by Andrija-Markovic** [comment]
Hi @sighphyre! I posted this comment thinking you might get a notification, but I am glad you still saw my comment. You are completely right about using WSL. My problem is solved using WSL. Thank you!

**Comment by sighphyre** [comment]
No worries! We do get notifications if you @ one of us but there's nothing with opening new issues if you're having problems, that also helps us keep our issues more manageable. Really glad you came right!
